### PR TITLE
[Windows] Remove app cut at the bottom and force refresh when back from fullscreen

### LINKED ISSUE #228: Fullscreen problem: previous screen visible at the bottom when pushing new screen
1. First page is red. 
2. Second page is green.

When I push the green page over the red one, there's a small gap running along the bottom edge of the screen where you can see the previous page (red line). This seems to only happen in fullscreen.

Fullscreen_issue

I am working at 1920 x 1080px resolution and my screen is 1920 x 1080px. 

I'm using Flutter 3.3.2 with window_manager 0.2.7.

Here's the code:

```
import 'package:flutter/material.dart';
import 'package:window_manager/window_manager.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Must add this line.
  await windowManager.ensureInitialized();

  WindowOptions windowOptions = const WindowOptions(
    size: Size(1920, 1080),
    center: true,
    backgroundColor: Colors.transparent,
    skipTaskbar: false,
    titleBarStyle: TitleBarStyle.hidden,
    fullScreen: true,
  );

  windowManager.setResizable(false);

  windowManager.waitUntilReadyToShow(windowOptions, () async {
    await windowManager.show();
    await windowManager.focus();
  });

  runApp(const MyApp());
}

class MyApp extends StatefulWidget {
  const MyApp({super.key});

  @override
  State<MyApp> createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        debugShowCheckedModeBanner: false,
        home: Scaffold(
            backgroundColor: Colors.red,
            body: Builder(
              builder: (context) => ElevatedButton(
                  onPressed: () => Navigator.push(
                        context,
                        MaterialPageRoute(
                            builder: (context) => const Scaffold(
                                  backgroundColor: Colors.green,
                                  body: SizedBox(),
                                )),
                      ),
                  child: const Text("Push new page")),
            )));
  }
}
```

### LINKED ISSUE #237: On the Windows platform, there is a white space at the bottom of the full screen window
## window_manager_plugin.cpp
```
std::optional<LRESULT> WindowManagerPlugin::HandleWindowProc(HWND hWnd,
                                                             UINT message,
                                                             WPARAM wParam,
                                                             LPARAM lParam) {
  std::optional<LRESULT> result = std::nullopt;

  if (message == WM_NCCALCSIZE) {
    // This must always be first or else the one of other two ifs will execute
    //  when window is in full screen and we don't want that
    if (wParam && window_manager->IsFullScreen()) {
      NCCALCSIZE_PARAMS* sz = reinterpret_cast<NCCALCSIZE_PARAMS*>(lParam);
      sz->rgrc[0].bottom -= 3;
      return 0;
    }
   
   ...
   ...
}

```

**sz->rgrc[0].bottom -= 3;**   

Can you tell me why the bottom margin of 3px should be reserved?

Thanks

### LINKED ISSUE #266: Fullscreen/Set as frameless bugs mediaQuery screen sizes
Setting fullscreen or frameless causes mediaquery to report back incorrect screen sizes.

To Test: 
Set frameless.
Call mediaQuery.of(context).size to get screen dimensions
Create transparent container with a thin coloured border of 0.5 based on mediaquery results
- The coloured perimeter line disappears on certain sides, usually the bottom, suggesting the mediaquery is not reporting the actual visible window size.

### LINKED ISSUE #311: wrong layout after exiting FullScreen
Hi,
There is a bug, you can reproduce it through below steps:
1. Run official example.
2. Set FullScreen.
3. Exit FullScreen.
4. Check the close button on the top right corner, it should be as below:
image

Thank you.

### LINKED ISSUE #355: Full screen mode is always failing by a few pixels on bottom of the screen
I'm executing on Windows 10. Always a few pixels line is showing at the bottom of the screen making visible the next windows on the stack. I searched on Google and somebody gets the same error. Any suggestion?

https://stackoverflow.com/questions/73229175/flutter-window-manager-fullscreen-embedded-webview-windows-not-displaying-fullsc

### PR DESCRIPTION
**Pull request by damywise**
- Removes the line that `cuts the app at the bottom by the pixel to prevent jitter when resizing app`
- Remove the line that `cuts the app by 3 pixels at the bottom when full screen`
- Fix #311
- Fix #266 
- Fix #228 
- Fix #355 
- Fix #237

NOTE: I have not tested this on Windows 10

### CODE REVIEW

File: windows/window_manager_plugin.cpp [hunk 1]
```diff
@@ -116,8 +116,6 @@ std::optional<LRESULT> WindowManagerPlugin::HandleWindowProc(HWND hWnd,
     // This must always be first or else the one of other two ifs will execute
     //  when window is in full screen and we don't want that
     if (wParam && window_manager->IsFullScreen()) {
-      NCCALCSIZE_PARAMS* sz = reinterpret_cast<NCCALCSIZE_PARAMS*>(lParam);
-      sz->rgrc[0].bottom -= 3;
       return 0;
     }
```
Comment (alexmercerind) [inline windows/window_manager_plugin.cpp:121]: While we're at it, can we add one more condition to ignore `WM_NCCALCSIZE` handling?

It won't break the plugin; we are implementing our in-house fullscreen mechanism in [`package:media_kit`](https://github.com/alexmercerind/media_kit/pull/250); and it will be great to have it compatible with [`package:window_manager`](https://github.com/leanflutter/window_manager).

```suggestion

    if (!(GetWindowLongPtr(hWnd, GWL_STYLE) & WS_OVERLAPPEDWINDOW))
      return 0;
    }
```

**Review by alexmercerind — COMMENTED** [review]
One more feedback:

In the current fullscreen implementation for Win32, you'll notice that window behaves oddly if you make the fullscreen while the window is maximized. It kind of flickers back to restored mode before going fullscreen.

Please use [this fullscreen implementation](https://github.com/alexmercerind/media_kit/blob/1226bcff36eab27cb17d60c33e9c15ca489c1f06/media_kit_video/windows/utils.cc
). The most stable that can be achieved.


Forget the license; you have my permission.

**Comment by alexmercerind** [comment]
Thanks!

**Comment by damywise** [comment]
Hi @alexmercerind, thank you so much for your review! Unfortunately, I am unable to implement nor test your changes and suggestions since I made this pull request during the only 3 days I had access to a Windows machine.
I currently don't have access to it until maybe 2 weeks, sorry about that!
Also I don't have a working Windows VM so, yeah, gonna take quite a while.

**Comment by lijy91** [comment]
LGTM
